version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventos-nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
